GetByExactName
ChepeUAQ/SistemasDistribuidos_JMMG pull request #12
Opened 2024-09-26 02:51 UTC by ChepeUAQ

2024-09-26 02:55 UTC, Jessfer68 requested changes

2024-09-26 02:55 UTC, Jessfer68 commented on RestApi/RestApi/Controllers/GroupsControllers.cs
> +    [HttpGet("like-name")]
Esto dejalo como estaba

2024-09-26 02:55 UTC, Jessfer68 commented on RestApi/RestApi/Controllers/GroupsControllers.cs
> +    [HttpGet("exact-name")]
Elimina este, por que solamente les pedi que crearan el metodo en el repositorio. NO que crearan el controller

2024-09-26 03:56 UTC, ChepeUAQ commented on RestApi/RestApi/Controllers/GroupsControllers.cs
> +    [HttpGet("exact-name")]
Listo profe, ya realice los cambios

2024-10-25 21:29 UTC, Jessfer68 approved these changes

2024-11-05 19:28 UTC, merged